Rewrite source range `highlight()`
`highlight()` now always prints whole lines of source code, and can
highlight arbitrary ranges using box drawing characters, not just with
ANSI colors.

Use this to fix diagnostic printing so that it's comprehensible in
a non color terminal and so that pasting errors into non-color
environments works.

The box drawing characters from WGL4 seem like a good balance of:

* Relatively compatible because they're very old, dating from DOS era:
  https://en.wikipedia.org/wiki/Box-drawing_character#DOS - note we also
  use these for formatting log messages from Logging.ConsoleLogger.

* Easy to distinguish from the user's source code

I've also found it's helpful to prepend any lines of annotation with a
Julia # comment where possible - this ensures that copy+paste into
websites with syntax highlighting will highlight the annotations
separately from the code.

A simple example:

    julia> (x - (c <--- d))
    ERROR: ParseError:
    (x - (c <--- d))
    #       └──┘ ── invalid operator @ REPL[48]:1:9

Also some semi-related changes included

* Generalized/expanded _printstyled() function
* Better diagnostic range for try-without-catch